# Generated by Django 5.2.1 on 2025-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_old_price_alter_product_is_discounted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='discounts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_discounted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
